---
development:
  cloud_name: dldrbqahx
  api_key: '513585899397739'
  api_secret: LoA9ztbpHN3SXqmqyanubuTuafY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dldrbqahx
  api_key: '513585899397739'
  api_secret: LoA9ztbpHN3SXqmqyanubuTuafY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dldrbqahx
  api_key: '513585899397739'
  api_secret: LoA9ztbpHN3SXqmqyanubuTuafY
  enhance_image_tag: true
  static_file_support: false
